- _posts/2015/2015-01-23-failure-and-repair.markdown
- _posts/2015/2015-02-07-failure-and-repair.markdown
> WIP: failure and repair

- _posts/2015/2015-03-28-download-nuget-package-licenses.markdown
Based on Stephen comment http://haacked.com/archive/2015/03/28/download-nuget-package-licenses/#comment-1935626688
> Update PowerShell base on comments

- _posts/2015/2015-06-15-the-getting-better-moment.markdown
https://solien.com URL does not resolve. Changed to http://www.solien.com
> solien.com broken link

- _posts/2015/2015-07-20-ghfvs-oss.md
> Initial draft of ghfvs oss post

- _posts/archived/2009-12-07-localizing-aspnetmvc-validation.aspx.markdown
> Add redirect for old post

- _posts/archived/2007-03-12-custom-configuration-sections-in-3-easy-steps.aspx.markdown
The Puralsight links to Craig Andera's article appear to have gone by the wayside. I found his Google Site page and referenced that and the link to the article there.
> Update broken links

- _posts/2015/2015-03-25-manager-bullshit.markdown
Browsing through your archive and I noticed a small typo.  Having just read your post about transferring your blog to Jekyll and asking for typo pull requests (http://haacked.com/archive/2013/12/02/dr-jekyll-and-mr-haack/), I figured I'd do just that!
> Small typo fix

- _posts/2017/2017-08-30-endless-immensity-of-the-sea.md
- _posts/2017/2017-08-31-endless-immensity-of-the-sea.md
Writing about leadership and intrinsic motivation.
> Endless immensity

- _posts/2017/2017-10-07-managers-gone-bad.md
A post about management theories.
> When good managers go bad

- _posts/2017/2017-10-20-gitcoin.md
A tongue in cheek approach to choosing a new project maintainer
> Git coin blog post

- _posts/archived/2012-12-17-you-do-not-need-a-thick-skin.aspx.markdown
cray -> crazy and a missing space
> minor typos in thick-skin

- Gemfile.lock
- _includes/post/edit.html
- _includes/post/sharing.html
- _layouts/post.html
> Make it more clear how to suggest an edit

- _data/comments/comments-for-jekyll-blogs/ad66d405.yml
> Comment by Phil Haack on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/1aeca214.yml
avatar: <img src="https://github.com/pedrolamas.png" width="64" height="64" />
I would think you can use the Content Moderator from Azure Cognitive Services to do the spam filtering for you! :)
> Comment by Pedro Lamas on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/3c1907bc.yml
avatar: <img src="https://github.com/damieng.png" width="64" height="64" />
Yes, it is a great idea!
> Comment by Damien Guard on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/ebcff92b.yml
avatar: <img src="https://secure.gravatar.com/avatar/4a15382e0aa463633427cd4da2443caa?s=80&d=identicon&r=pg" width="64" height="64" />
(thumbsup)
> Comment by Dennis on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/9de481af.yml
avatar: <img src="https://secure.gravatar.com/avatar/40e6d0c1dc7a6af05d55a13fbfa4a4ac?s=80&d=identicon&r=pg" width="64" height="64" />
Just checking your comment system.
> Comment by Arnab on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/dfa316d9.yml
avatar: <img src="https://github.com/smack0007.png" width="64" height="64" />
I've been looking for a reason to leave a comment on your blog for years.
> Comment by smack0007 on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/c1e86adf.yml
avatar: <img src="https://avatars.io/twitter/@travislaborde/medium" width="64" height="64" />
so, someone can increase their "open source contributor" rankings by commenting on your blog?  nice!  I've contributed to the Haacked Blog!
> Comment by Travis Laborde on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/7b49647e.yml
avatar: <img src="https://secure.gravatar.com/avatar/2f03964dccb20338f7a962fa270cdb02?s=80&d=identicon&r=pg" width="64" height="64" />
Great read and an excellent idea :) I also appreciate caring about what kinds of Ads your audience are exposed to.  Wish more blogs do the same.
Thanks also Phil for sharing this project; I always learn something  new from your blog AND from the comments aswell :) 
> Comment by Mohamoud on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/4d351f45.yml
I realize now that if I have a popular blog post, I will have a lot of PRs to merge!
> I would think you can use the Content Moderator from Azure Cognitive Services to do the spam filtering for you! :)
Pedro, I may give that a try!
> A typical approach for poor man's comment filtering would be to include a Honeypot.
You mean, like this? https://haacked.com/archive/2007/09/11/honeypot-captcha.aspx/
I'll probably add something like that too.
> Comment by haacked on comments-for-jekyll-blogs

- _data/comments/uploading-files-with-aspnetmvc-aspx/a7207500.yml
avatar: <img src="https://secure.gravatar.com/avatar/0aa1be16f0d908900396bf31d60f0e7f?s=80&d=identicon&r=pg" width="64" height="64" />
i have an error of object instance when trying to use this code for multiple files upload
> Comment by Adeola on uploading-files-with-aspnetmvc-aspx

- _data/comments/comments-for-jekyll-blogs/85271786.yml
avatar: <img src="https://avatars.io/twitter/@imaya/medium" width="64" height="64" />
Really nice. Let the testing begin.. Test 1 :)
> Comment by Imaya on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/3cc289a7.yml
avatar: <img src="https://secure.gravatar.com/avatar/e7bf0069082c6c45a33d18500fd95354?s=80&d=identicon&r=pg" width="64" height="64" />
Phil, nice to run into you again. I have been a silent follower of your content back in my .NET days. I had to double check to see if was the same person but how many Haacks are there? Anyhow, I'm investigating the same solution for my Hugo blog which led me to your article. I do like the pull-request idea of Staticman but wish it was more comprehensive and supported Bitbucket. I'm seriously thinking about scratching this itch myself. How big do you believe the need is out there?
> Comment by Michael on comments-for-jekyll-blogs

- _data/comments/current-directory-for-windows-service-is-not-what-you-expect-aspx/91889300.yml
avatar: <img src="https://secure.gravatar.com/avatar/5d73edfb2931abb1ef9dc4fc92edbb71?s=80&d=identicon&r=pg" width="64" height="64" />
Great point!! Thanks.
> Comment by Diego on current-directory-for-windows-service-is-not-what-you-expect-aspx

- _data/comments/comments-for-jekyll-blogs/59ce41fd.yml
avatar: <img src="https://avatars.io/twitter/@dsschnau/medium" width="64" height="64" />
That's rad
> Comment by DAn on comments-for-jekyll-blogs

- _data/comments/comments-for-jekyll-blogs/405c36c5.yml
avatar: <img src="https://secure.gravatar.com/avatar/bcf5cfd10102f3044df3a1e7e5231ce9?s=80&d=identicon&r=pg" width="64" height="64" />
This is a really nice write-up. Also, thanks to commenters for mentioning Staticman.
> Comment by Jarod on comments-for-jekyll-blogs

- _data/comments/url-routing-debugger-aspx/26a4c60e.yml
avatar: <img src="https://secure.gravatar.com/avatar/00c57c63f307f4169df10eea25f75a1b?s=80&d=identicon&r=pg" width="64" height="64" />
Just used this, worked fine for me with the web.config setting. Helped me to spot the problem very quickly.. probably saving me hours of head-scratching. THANKYOU FOR BUILDING THIS!
> Comment by Andy on url-routing-debugger-aspx

- _posts/2018/2018-07-11-abolish-performance-reviews.md
TL;DR They're awful and companies should stop doing them.
> Write post about performance reviews

- _data/comments/abolish-performance-reviews/106c8bae.yml
avatar: <img src="https://secure.gravatar.com/avatar/a2c86dad71023f9f4124434b1b7da60f?s=80&d=identicon&r=pg" width="64" height="64" />
"Pay according to the market instead." What ever happened to paying what your worth?
> Comment by Travis on abolish-performance-reviews

- _data/comments/abolish-performance-reviews/2d0e5214.yml
avatar: <img src="https://secure.gravatar.com/avatar/4b45f26b105eea5a7a0a38571d0a778d?s=80&d=identicon&r=pg" width="64" height="64" />
Performance reviews are the same thing as putting up signs around a company every few feet that read:
"The beatings will continue until morale improves."
> Comment by PoB on abolish-performance-reviews

- _data/comments/abolish-performance-reviews/fcd7f360.yml
avatar: <img src="https://secure.gravatar.com/avatar/b0d8c6e5ea589e6fc3d3e08afb1873bb?s=80&d=identicon&r=pg" width="64" height="64" />
Travis:
> What ever happened to paying what your worth?
Interesting question, I think that it is far to be possible, and in that case, we would require these toxic reviews, right? I would like to hear Phil answer.
> Comment by John Smith on abolish-performance-reviews

- _data/comments/abolish-performance-reviews/bac29949.yml
avatar: <img src="https://avatars.io/twitter/@yawaramin/medium" width="64" height="64" />
@Jeff Jones: 'I understand many of the younger employees are not used to being told their idea is worthless and that they are not putting in the effort they should.'
I'm pretty sure Deming wasn't talking about millennials when he said that performance reviews are bad.
@Shane Bray: 'Perhaps because I’ve NEVER had a bad one. And that, perhaps, is because I welcome criticism and negative feedback.'
You are a textbook case of the survivorship bias mentioned in the post ;-) Also, if you've never had a bad review, how do you actually know that you welcome it?
> Comment by Yawar on abolish-performance-reviews

- _data/comments/reviewing-merge-commits/0a647018.yml
avatar: <img src="https://secure.gravatar.com/avatar/a63d01e7ff1962585ede95d6ee5369b5?s=80&d=identicon&r=pg" width="64" height="64" />
Great article. I recently logged a feature request for Sourcetree referring this article https://jira.atlassian.com/browse/SRCTREEWIN-8959
Note that feature request for TortoiseGit was already referring this article
https://gitlab.com/tortoisegit/tortoisegit/issues/2469
> Comment by Abdul Rauf on reviewing-merge-commits

- _data/comments/abolish-performance-reviews/024b8147.yml
avatar: <img src="https://avatars.io/twitter/@mandywhaley/medium" width="64" height="64" />
Great post
> Comment by Mandy Whaley on abolish-performance-reviews

- _data/comments/current-directory-for-windows-service-is-not-what-you-expect-aspx/ec36bc51.yml
avatar: <img src="https://secure.gravatar.com/avatar/44f082ab39a0effff854b81593398ea6?s=80&d=identicon&r=pg" width="64" height="64" />
How to change that when we install a new exe as a Windows Service?
> Comment by Sam on current-directory-for-windows-service-is-not-what-you-expect-aspx

- _data/comments/abolish-performance-reviews/ec6d03f4.yml
avatar: <img src="https://avatars.io/twitter/@abraham/medium" width="64" height="64" />
I agree
> Comment by abraham on abolish-performance-reviews

- _data/comments/razor-syntax-quick-reference-aspx/ec48d9b2.yml
avatar: <img src="https://secure.gravatar.com/avatar/0a82d7455bf0d638e80b281d1c309ace?s=80&d=identicon&r=pg" width="64" height="64" />
how to add a parameter to an html tag?
> Comment by Guillermo J Perez on razor-syntax-quick-reference-aspx

- _data/comments/comments-for-jekyll-blogs/9b2e8797.yml
avatar: <img src="https://github.com/gayanw.png" width="64" height="64" />
Thanks. Will try it on my blog.
> Comment by Gayan Weerakutti on comments-for-jekyll-blogs

- _data/comments/cocommentsupportinsubtext-aspx/849caecd.yml
@Sergey I'm using this now: https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/
> Comment by haacked on cocommentsupportinsubtext-aspx

- _data/comments/comments-for-jekyll-blogs/eb0262fb.yml
avatar: <img src="https://secure.gravatar.com/avatar/e22bc1c81438795dcbc918a4c6e16b57?s=80&d=identicon&r=pg" width="64" height="64" />
wow
> Comment by Horace on comments-for-jekyll-blogs

- _data/comments/cocommentsupportinsubtext-aspx/e626c683.yml
avatar: <img src="https://github.com/fake.png" width="64" height="64" />
@haacked Thanks! I hope you don't mind that I mentioned your post as a demo for this commenting system at [open-source-comments](https://lisakov.com/projects/open-source-comments/).
> Comment by Sergey on cocommentsupportinsubtext-aspx

- _data/comments/model-binding-to-a-list-aspx/a72f3c31.yml
avatar: <img src="https://secure.gravatar.com/avatar/6b236c7efba9ea1a89002d3165cbcb0f?s=80&d=identicon&r=pg" width="64" height="64" />
If every row has same value for name attribute (products.Index), form post will consider it as one element. How does it handle here?
> Comment by Kamalpreet Singh on model-binding-to-a-list-aspx

- _data/comments/github-flow-aliases/0d5c0ee1.yml
avatar: <img src="https://github.com/chhh.png" width="64" height="64" />
The flow of explanation is so smooth, a pleasure reading and copy-pasting into my own include file. Thanks!
> Comment by chhh on github-flow-aliases

- _data/comments/comments-for-jekyll-blogs/44c88994.yml
avatar: <img src="https://secure.gravatar.com/avatar/ff5a13b37fd8ebc821088528d23b5987?s=80&d=identicon&r=pg" width="64" height="64" />
Just leaving a comment to test this out. Apologies.
> Comment by Seanba on comments-for-jekyll-blogs

- _data/comments/github-flow-aliases/dea9e375.yml
avatar: <img src="https://github.com/sovrinbloc.png" width="64" height="64" />
Grabbed a couple great ones from here!
> Comment by Joe on github-flow-aliases

- _data/comments/routedebugger-2-aspx/c0b40ed0.yml
avatar: <img src="https://secure.gravatar.com/avatar/0ea7c6f624bb04a950a39da81d93f600?s=80&d=identicon&r=pg" width="64" height="64" />
Hi, I've been trying to use this debugger for some time now, but i just can't figure out how to get it to show my routes. My project i split up, so i have one project with it's own localhost, which my second project listens to. How do i get my routes shown?
> Comment by Mathias on routedebugger-2-aspx

- _data/comments/custom-configuration-sections-in-3-easy-steps-aspx/d143bc99.yml
avatar: <img src="https://github.com/jaypatrick.png" width="64" height="64" />
11 years later, and this is still a go to post for me for wiring up simple configuration settings. Is there a new mechanism to do this though?
> Comment by Jayson Knight on custom-configuration-sections-in-3-easy-steps-aspx

- _data/comments/moq-sequences-aspx/ae62467d.yml
avatar: <img src="https://github.com/ktabarez.png" width="64" height="64" />
With the new version of Mock you can now use SetupSequence:
// taken from: https://github.com/Moq/moq4/wiki/Quickstart#miscellaneous
var mock = new Mock<IFoo>();
mock.SetupSequence(f => f.GetCount())
.Returns(3)  // will be returned on 1st invocation
.Returns(2)  // will be returned on 2nd invocation
.Returns(1)  // will be returned on 3rd invocation
.Returns(0)  // will be returned on 4th invocation
I thought I should post this because this was one of the top google search results which at the time was a nice solution to mocking sequential method calls :)
> Comment by ktabarez on moq-sequences-aspx

- _data/comments/fixing-binding-to-decimals-aspx/8f734e0d.yml
avatar: <img src="https://secure.gravatar.com/avatar/27471e5fcf29971106b2ed38a258dbf0?s=80&d=identicon&r=pg" width="64" height="64" />
Thanks for this, it saved me!
> Comment by Jim on fixing-binding-to-decimals-aspx

- _data/comments/model-binding-to-a-list-aspx/22eda56f.yml
avatar: <img src="https://secure.gravatar.com/avatar/1d40172d1e35566dc321a04b5d20ce66?s=80&d=identicon&r=pg" width="64" height="64" />
Thank you, Phil Haack, for this, even a decade later, especially for the html example under Non-Sequential Indices!
> Comment by Aaron T on model-binding-to-a-list-aspx

- _includes/comment.html
Sometimes folks ask me to delete or edit their comment. It's kind of a pain to find it. At least now I can view source and find it.
> Comment the URL for the comment

- _data/comments/comments-for-jekyll-blogs/22c024e4.yml
Former-commit-id: 96f70dccfbcb598ef25b7a0a411e10201595084c
> Comment by Andrew Gunn on comments-for-jekyll-blogs

- _data/comments/uploading-files-with-aspnetmvc-aspx/9b2c6b7b.yml
Former-commit-id: d70b23240f47fae8633c7c9af0dddb7ee574a5df
> Comment by Ronald on uploading-files-with-aspnetmvc-aspx

- _data/comments/how-to-stop-a-thread-aspx/90483da1.yml
Former-commit-id: afd9177e6c388ce11c935b5180cc75ed0393bf35
> Comment by Ivan Ferrer on how-to-stop-a-thread-aspx

- _posts/2018/2018-11-15-finding-new-job.markdown
A post with a bit of advice to give
> Land first job

- _scss/screen.scss
- contributors/index.markdown
This spruces up the contributors page a bit
> Add CSS class for contributor list

- _posts/2018/2018-12-03-css-column-list-adventure.markdown
> Updating typo

- _posts/2018/2018-12-18-leaving-github.markdown
A post about my time at GitHub.
> Leaving GitHub

- _posts/2018/2018-12-18-leaving-github.markdown
> fix: spelling

- _posts/2018/2018-12-18-leaving-github.markdown
> fix: grammar

- _posts/2018/2018-12-18-leaving-github.markdown
hint, hint, choosealicense.biz is available... :smile:
> choosealicense.com, not choosealicense.org

- _posts/2019/2019-01-07-haacked-llc.markdown
- _posts/archived/2016/2016-04-28-thank-you.markdown
A little bit about what I'm up to.
> A post about my new company - Haacked LLC

- _posts/2019/2019-03-27-nuget-package-signing.markdown
- _posts/2019/2019-04-03-nuget-package-signing.markdown
A look at the NuGet package signing feature.
> Nuget signature exploration

- _posts/2019/2019-04-03-nuget-package-signing.markdown
Add details on the `-owners` option.
> Nuget package signing update

- _posts/2019/2019-05-24-event-stream.markdown
- _posts/2019/2019-05-28-maintainer-burnout.markdown
I'll probably finish this up next week.
> Post about deep mitigation of package vulnerabilities

- _posts/2019/2019-05-30-github-for-dummies.markdown
Removed an additional "at" that doesn't look like it's supposed to be there.
> Fix small typo

- _posts/2019/2019-06-10-team-discussions.markdown
> Initial draft of team discussions post

- _posts/2019/2019-07-29-query-filter-by-interface.markdown
Blog post about applying a strongly typed query filter based on an interface.
> Query filter interface

- _posts/2019/2019-12-09-fun-with-url-encodings.markdown
Minor typo. Really enjoyed the article and history lesson. I've wondered why there were so many ways to do that.
> Fixed typo: scenario

- pages/about.md
You had the phrase "started off as my my blogger handle".
Thanks for the helpful blog!
> Removed duplicate word

- _posts/2020/2020-04-17-break-to-build.markdown
> because ~~he's~~ I believe he's
> Fixed typo

- _posts/2020/2020-05-17-french-thousand-separator-mystery.md
A detective story involving a failing unit test. A test that passes the build, but fails on my machine. And how the Unicode Consortium is at the center of it all.
> Write post of the mysterious thousands separator

- _posts/archived/2012/2012-04-09-reactive-extensions-sample.aspx.markdown
Just happened to stumble upon this, and confirmed with Ani that she was cool with me submitting this PR.
> Update name / link

- _posts/2020/2020-11-24-naming-nuget.markdown
Fixed a couple of typos.  Also, I suggest changing the phrase `If you get expose a proposal` to `If you can expose a proposal` for clarity.
> Fix typos, change phrasing for clarity

- _posts/2021/2021-02-11-introducing-abbot.markdown
A post about ChatOps and the product we made to realize it.
> Introducing abbot

- _posts/2021/2021-02-11-introducing-abbot.markdown
- _posts/2021/2021-02-12-argument-parsing-with-abbot.markdown
- _posts/2021/2021-02-19-writing-abbot-skill-in-csharp.markdown
Some posts had tags that were separated by space and not a comma, so I replaced it with a comma.
> Fix issue with tags on some posts

- _posts/2020/2020-03-09-geographically-distributed-teams.markdown
Fixed typos in 2020-03-09-geographically-distributed-teams.markdown
> Fixed typos

- _data/comments/razor-syntax-quick-reference-aspx/6ec3168e.yml
avatar: <img src="https://secure.gravatar.com/avatar/7dacbacb3c3d2184161fd98354c7e9aa?s=80&d=identicon&r=pg" width="64" height="64" />
This is a suggestion, but what about adding a third column with the actual result in the rendered page? Also, I'm making this comment on 2022, so I don't know if this need an update or not.
> Comment by Carlos on razor-syntax-quick-reference-aspx

- _data/comments/model-binding-to-a-list-aspx/b51f314b.yml
> Comment by Khaled on model-binding-to-a-list-aspx

- _data/comments/current-directory-for-windows-service-is-not-what-you-expect-aspx/ba9f8652.yml
Thanks man. It really helped me
> Comment by marlon on current-directory-for-windows-service-is-not-what-you-expect-aspx

- _data/comments/clickablebackgroundimagesviacss-aspx/1606f8eb.yml
avatar: <img src="https://secure.gravatar.com/avatar/e9269665b6b9cc6c975ad23458a62b59?s=80&d=identicon&r=pg" width="64" height="64" />
Still relevant :)
> Comment by t on clickablebackgroundimagesviacss-aspx

- _data/comments/i-knew-how-to-validate-an-email-address-until-i-aspx/e1096cdc.yml
I'm so glad I ended up reading this. I had no idea until I heard a podcast reference an RFC about e-mail. Nice.
> Comment by Allen in Iowa on i-knew-how-to-validate-an-email-address-until-i-aspx

- _posts/2020/2020-09-28-azure-swap-with-warmup-aspnetcore.md
Thanks for your blog post - super helpful!
As I was implementing this approach in my code, I found a minor mistake - in the `IsStatusCheckRequest` method.
HTH
> Use correct param in IsStatusCheckRequest

- _data/comments/the-dangers-of-implementing-recurring-background-tasks-in-asp-net-aspx/f347e033.yml
avatar: <img src="https://unavatar.now.sh/twitter/coderanger/" width="64" height="64" />
Jeff Atwood posted a great solution to a simple background task for asp.net at https://stackoverflow.blog/2008/07/18/easy-background-tasks-in-aspnet/
> Comment by Dan Petitt on the-dangers-of-implementing-recurring-background-tasks-in-asp-net-aspx

- _data/comments/ef-core-collection-pitfalls/0fda8dc4.yml
Thanks! Why doesn't the Count method and other enumerating methods automatically load the data if itvs not loaded?
> Comment by Joel on ef-core-collection-pitfalls

- _data/comments/how-would-you-maximize-profit-from-a-time-machine-aspx/35ff4543.yml
Interestingly, I'm in the future world of the 2020s, and from here, an answer that meets all constraints and performs exceptionally well is: go to 2010, set up a bitcoin wallet (or a few dozen), and buy $10000 worth.
When you get back to 2022, you'll be the wealthiest person on the planet; it will be untraceable, but will still work so long as you still have your keys.
> Comment by John Smith on how-would-you-maximize-profit-from-a-time-machine-aspx

- _data/comments/csharp-list-pattern/1e82abe7.yml
I feel like perhaps the odd one out, but I rather dislike the new syntax; for single item I much prefer the "before" and for multiple - well, I don't like either :D
> Comment by Richard Moss on csharp-list-pattern

- _data/comments/csharp-list-pattern/5e450cdd.yml
avatar: <img src="https://secure.gravatar.com/avatar/7571499633d18bc330ab7d1ba231dc27?s=80&d=identicon&r=pg" width="64" height="64" />
Yea.. I agree with Richard Moss.
> Comment by SDK on csharp-list-pattern

- _data/comments/video-richard-simmons-visits-whose-line-is-it-anyway-aspx/3142c2fd.yml
avatar: <img src="https://secure.gravatar.com/avatar/121520349d9583c559ec384a0a7543dc?s=80&d=identicon&r=pg" width="64" height="64" />
Really?  Someone who doesn't think this is one of the funniest skits on television ever watched it half a dozen times????  WTF??!!  MASOCHIST!!!!
> Comment by IQ on video-richard-simmons-visits-whose-line-is-it-anyway-aspx

- _data/comments/scoping-db-context/6ee8b6f9.yml
> Comment by Bryan on scoping-db-context

- _data/comments/scoping-db-context/edec190e.yml
avatar: <img src="https://robohash.org/cd501cd68783e22d1c0f564b98c19166" width="64" height="64" />
Thanks for this article. I wrote the Entity Framework Core in Action book, but I never came across this issue. This sort of article is so useful to people, and me!
> Comment by Jon P Smith on scoping-db-context

- _data/comments/haackbar-theme/2e323a25.yml
avatar: <img src="https://secure.gravatar.com/avatar/24047f32bb374dcff3c6804a95f20a47?s=80&d=identicon&r=pg" width="64" height="64" />
You host on GitHub? Cool. I'm looking into now. But how do you have your own DNS (haacked.com) pointing there (to GitHub pages)?
> Comment by PHenry on haackbar-theme

- _data/comments/remote-desktop-file-copy-aspx/f07a9106.yml
> Comment by Hjr on remote-desktop-file-copy-aspx

- _data/comments/debunking-peter-principle/2c8a04c1.yml
avatar: <img src="https://secure.gravatar.com/avatar/d8151794c846907c473c2c6342eefd5b?s=80&d=identicon&r=pg" width="64" height="64" />
That was the conclusion I reached when I was told about Peter's principle by a business major . I was a college sophomore .  Look at each level as it happens.
> Comment by Berny D on debunking-peter-principle

- _data/comments/geek-your-momma-jokes-aspx/f538abde.yml
yo mama so fat that when she went to In-N-Out Burger she couldn't get in or out
> Comment by dabomb on geek-your-momma-jokes-aspx

- _data/comments/geek-your-momma-jokes-aspx/fbacb5b8.yml
avatar: <img src="https://secure.gravatar.com/avatar/5c5b8090f1ddaf9cd3ecb309dcafaaa6?s=80&d=identicon&r=pg" width="64" height="64" />
ur mom is so stupid she returned a donut to the store because it had a hole in it.
> Comment by Coleeeeeeee77777777777777 on geek-your-momma-jokes-aspx

- _data/comments/calling-internal-ctors/3f9ed83a.yml
avatar: <img src="https://github.com/aelij.png" width="64" height="64" />
You may want to give this utility package I made a try. It's not a perfect solution but has saved me more than a few times.
https://github.com/aelij/IgnoresAccessChecksToGenerator
> Comment by Eli on calling-internal-ctors

- _posts/2022/2022-11-07-so-you-want-to-speak-at-conferences.md
Changed "differenc" -> "difference"
> Fix typo in 2022-11-07-so-you-want-to-speak-at-conferences.md

- _data/comments/https-for-azure-functions/52cb1c76.yml
avatar: <img src="https://secure.gravatar.com/avatar/03f261f79c97c2cae937282b8ec99209?s=80&d=identicon&r=pg" width="64" height="64" />
Unfortunately, Microsoft is dropping support for Proxies in Azure Functions ;-(
> Comment by Alex on https-for-azure-functions

- _data/comments/bin-deploy-aspnetmvc-aspx/40cc37f4.yml
avatar: <img src="https://secure.gravatar.com/avatar/244537590c9c81aed99fbe149a7ff161?s=80&d=identicon&r=pg" width="64" height="64" />
this still works on vs2010 mvc2 published on the file system and then copied to a win2k19 running iis10.
> Comment by appsdevm on bin-deploy-aspnetmvc-aspx

- _data/comments/failure/0d80f382.yml
avatar: <img src="https://secure.gravatar.com/avatar/304ced7cb1c3e1787b8f98b6e4547ca9?s=80&d=identicon&r=pg" width="64" height="64" />
I am so sorry to hear that happened to you Phil, I’ve never been brave enough to attempt what you tried to do!
> Comment by David  on failure

- _data/comments/failure/04332b4d.yml
avatar: <img src="https://github.com/CBenghi.png" width="64" height="64" />
I never met you in person, but you are an one individual I always look up to. I'm sure there are more great things to come from your side. Keep it up.
> Comment by Claudio on failure

- _data/comments/failure/08af3da6.yml
avatar: <img src="https://secure.gravatar.com/avatar/270e72d34a3b7a634077333a37087000?s=80&d=identicon&r=pg" width="64" height="64" />
I remember when you were working on Koders and I was evaluating it for my org. There was a strong customer need and the solution, while not unique (I think Black Duck were the competition, and didn't they acquire Koders in the end?), it was compelling because it understood the user need more that the competition.
I've worked with lots of start-ups / scale-ups / successful mature businesses over my 20+ years in consulting and one thing has always struck me - the technology doesn't matter. I've seen some insanely successful products that are an absolute horror show behind the scenes (technology / people / processes), but it never really mattered because they …
> Comment by Howard van Rooijen on failure

- _data/comments/geek-your-momma-jokes-aspx/676f769c.yml
Your mama so fat that Kirby couldn’t inhale her
> Comment by Juju on geek-your-momma-jokes-aspx

- _data/comments/failure/be93ca49.yml
avatar: <img src="https://secure.gravatar.com/avatar/3b1ed3ccad08ed8c93c8bdaac65acb56?s=80&d=identicon&r=pg" width="64" height="64" />
Congratulations on having the guts to try! Hope all is well!
> Comment by Pat Gannon on failure

- _data/comments/failure/b565e9d3.yml
avatar: <img src="https://github.com/masaez.png" width="64" height="64" />
You talk about Argentina, and then ask to be sober on the next paragraph. There has to be some correlation there (?). Glad to see you create great stuff Phil! Even if it fails!
> Comment by Miguel Saez on failure

- _data/comments/geek-your-momma-jokes-aspx/8d1fc3ba.yml
yo momma's so fat when she took a picture 1000000000000000 years later its still printing.
> Comment by nathaniel on geek-your-momma-jokes-aspx

- _data/comments/dotnet-aspire/e96cafcc.yml
avatar: <img src="https://github.com/erikbra.png" width="64" height="64" />
I think .NET Aspire Maps very well to helmfile, product wise. I think it tries to solve almost all the same problems, just in a different manner
> Comment by Erik A. Brandstadmoen on dotnet-aspire

- _data/comments/dotnet-aspire-vs-docker/55ab0936.yml
avatar: <img src="https://github.com/haacked.png" width="64" height="64" />
Whoops! I made it public now.
> Comment by Haacked on dotnet-aspire-vs-docker

- _data/comments/dotnet-aspire-vs-docker/a71321a4.yml
I think the "F5 to run experience" is worth a lot, will probably start using soon. (even though the added aspire projects makes me a bit sad)
> Comment by Johan Eriksson on dotnet-aspire-vs-docker

- _data/comments/dotnet-aspire-vs-docker/55c02011.yml
avatar: <img src="https://robohash.org/b49aabacfb5b9ab22461ba095f001061" width="64" height="64" />
Will be nice if they integrate with out of process db creation/migration platforms like SQL Server Data Tools or Flyway.  If not on EF there’s a big gap here.
> Comment by Steve Ognibene on dotnet-aspire-vs-docker

- _data/comments/octokit-oauth/6b94232f.yml
avatar: <img src="https://secure.gravatar.com/avatar/c331918bcc660584ee36ca2b2c992315?s=80&d=identicon&r=pg" width="64" height="64" />
Could you please point me in the right direction to do this using a C# .NET desktop application?
> Comment by Harry on octokit-oauth

- _posts/2022/2022-10-12-calculating-mrr-with-stripe-and-csharp.md
- _posts/2022/2022-11-22-csharp-list-pattern.md
- _posts/2022/2022-12-05-recover-from-dbupdate-exception.md
- _posts/2022/2022-12-12-specific-db-exception.md
- _posts/2023/2023-01-09-scoping-db-context copy.md
- _posts/2023/2023-05-01-calling-internal-ctors.md
- _posts/2024/2024-06-27-dotnet-aspire.md
- _posts/2024/2024-07-01-dotnet-aspire-vs-docker.md
- _posts/2024/2024-07-18-better-config-sections.md
> Fix blog post tags

- _posts/2024/2024-11-11-git-bisect.md
Why you should look at Git Bisect.
> Git bisect Blog Post

- _data/comments/chutes-and-ladder/d94bbeb4.yml
avatar: <img src="https://secure.gravatar.com/avatar/823048c003a3159b3adc1ee146b91114?s=80&d=identicon&r=pg" width="64" height="64" />
Congratulations Phil. You tried the different experiences and roles and you will be back to what you like the most. Titles are not everything.
> Comment by Abdu on chutes-and-ladder

- _data/comments/string-or-value/1ec3e229.yml
avatar: <img src="https://secure.gravatar.com/avatar/3992ceb74b3472c8a406a1100d357bf0?s=80&d=identicon&r=pg" width="64" height="64" />
Very useful, and thorough implementation - thanks for sharing StringOrValue<T>!
> Comment by David on string-or-value

- _data/comments/asp-net-tip---use-the-label-control-correctly-aspx/a5db4378.yml
avatar: <img src="https://secure.gravatar.com/avatar/13ff3cb875cc5c093f223c6adaa69fe8?s=80&d=identicon&r=pg" width="64" height="64" />
This post was helpful.  (I hated the fact in 2025 I still needed this knowledge)
> Comment by Joshua H on asp-net-tip---use-the-label-control-correctly-aspx

- _data/comments/new-year-new-job/b48311a4.yml
avatar: <img src="https://secure.gravatar.com/avatar/b3f282acb325f2b046db041a19baa710?s=80&d=identicon&r=pg" width="64" height="64" />
Congratulations. I love PostHog newsletter/blog. Hope you work with folks that prefer NO pineapple on their pizza (unless you like that sort of thing).
> Comment by Al Gonzalez on new-year-new-job

- _data/comments/new-year-new-job/9b573656.yml
avatar: <img src="https://secure.gravatar.com/avatar/66667a69651889dcb2d7d14efe84b028?s=80&d=identicon&r=pg" width="64" height="64" />
Every time I read your posts, I feel motivated and empowered. Thank you for the inspiration!
> Comment by kickboxingclasses on new-year-new-job

- _data/comments/posthog-dotnet-1-0/00280024.yml
avatar: <img src="https://haacked.com/assets/img/unknown-avatar.png" width="64" height="64" />
We were looking at PostHog and was a good candidate until we saw it did have support for Open Feature. Any plans of adding that?
> Comment by Mark on posthog-dotnet-1-0

- _data/comments/turkish-i-problem-and-why-you-should-care-aspx/e543b415.yml
avatar: <img src="https://haacked.com/assets/img/unknown-avatar.png" width="64" height="64" />
It's 2025 and even VS CODE has this problem. https://github.com/microsoft/vscode/issues/81826#issuecomment-2783550615
When Turkish people open an issue on github about it, they mark it as "not planned".
> Comment by R on turkish-i-problem-and-why-you-should-care-aspx

- _data/comments/css-column-list-adventure/3d9e19fc.yml
This article saved my day! Thank you for the hint with `display: inline-block` for columns-count!
> Comment by Artem on css-column-list-adventure

- _data/comments/semantic-merge/10e4d6b1.yml
avatar: <img src="https://secure.gravatar.com/avatar/36153fb945d4e7bd014cdf7f60ffd033?s=80&d=identicon&r=pg" width="64" height="64" />
Unfortunately, SemanticMerge seems to be gone, after they were bought by Unity.. :-(
> Comment by Tudor on semantic-merge
