_posts/2014/2014-12-09-unwrap-mef-exception.markdown

An alternative way to make the sentence grammatical would be to remove the comma before "but". However, this would have the effect of making "It" (the solution) be the subject of "would love"; as solutions are typically incapable of love, it is dubious that this is the author's original intended meaning. Therefore, the insertion of "I" is the fix that most likely preserves the author's intent.

Insert missing subject.

---

_includes/head.html

The title tag is duplicated in the default template.

Remove duplicate title tag

---

_posts/2015/2015-06-26-git-migrate.markdown
_posts/2015/2015-06-29-git-migrate.markdown

The final scenario I want to make work is when you want to migrate a commit range instead of every _local_ commit.
Here's the alias I have so far:
```bash
migrate = "!f(){ git branch $1 && git reset ${3-'@{u}'} --hard && git rebase --onto ${2-master} ${3-'@{u}'} $1; }; f"
```
Now take a look at this tree.
If I run `git migrate new-branch` everything works great. That would expand to the following commands:
```bash
git branch new-branch
git reset origin/wrong-branch --hard
git rebase --onto master origin/wrong-branch new-branch
```
And that seems to result correctly in `wrong-branch` being reset to `origin/wrong-branch` AND commits `E` and `F` (but not `D`) migrated to a branch `new-branch` off of master.
However, if I run `git migrate new-branch master HEAD~1` I would expect that …

Git migrate Blog post draft

---

_posts/2015/2015-06-29-git-migrate.markdown

- a more distinct separation of the master branch name and the command makes it clearer to read

easier to read

---

_posts/archived/2004-08-20-resharper-property-expansion-live-template.aspx.markdown

The post at /2005/10/17/WritingCustomExceptionsUsingResharperLiveTemplates.aspx links to /archive/2004/08/20/954.aspx, which should redirect to /archive/2005/10/17/WritingCustomExceptionsUsingResharperLiveTemplates.aspx.

Setup a redirect from an old URL

---

_posts/archived/2004-06-15-impedance-mismatch.aspx.markdown

Due to line wrapping, there was an extra `a` in the sentence.

a a a a a very easy to miss typo

---

_posts/archived/2007-08-21-i-knew-how-to-validate-an-email-address-until-i.aspx.markdown

"|" is often used to describe tables, and the list of valid characters is not a table (as far as I can tell.)
This would correct that minor typo.

Validate an email address: Escape "|"

---

_posts/archived/2007-08-21-i-knew-how-to-validate-an-email-address-until-i.aspx.markdown

Markdown processing is rendering these " characters as typographer's quotes (aka curly quotes, smart quotes, etc.), which is incorrect given the technical and character set-related nature of the discussion.

Correct quote rendering in example email addresses

---

_posts/archived/2005-05-30-thereisnoperfectdesign.aspx.markdown
_posts/archived/2006-08-09-asp.netsupervisingcontrollermodelviewpresenterfromschematictounitteststocode.aspx.markdown

These redirects_from lines appear to cause jekyll some unhappiness
Maybe something changed with case-(in)-sensitive directory names?
cc: @parkr

Fix from jldec

---

_posts/2015/2015-06-29-git-migrate.markdown

[The old one](http://pivotallabs.com/git-rebase-onto/) is being redirect to the new home page of the blog.

Update link to Pivotal's post about rebase --onto

---

_posts/2018/2018-01-27-analyze-github-issue-comment-sentiment.md

As I read it, I missed every single reference to the repo but this one, which looks wrong. It may still be useful to have a rendition of it as an URL-looking thing, but if so, it should probably be styled in some way (maybe by having the link text be simply `https://github.com/haacked-demos/azure-sentiment-analysis/` ?)

Linkify URL

---

_data/comments/comments-for-jekyll-blogs/9568c6ee.yml

avatar: <img src="https://avatars.io/twitter/@antariszx/medium" width="64" height="64" />
A typical approach for poor man's comment filtering would be to include a Honeypot. If the honeypot had a value, ditch the comment as it is likely automated crap.
Make the honeypot a visibly hidden (but not input:hidden)

Comment by Matthew Abbott on comments-for-jekyll-blogs

---

_data/comments/comments-for-jekyll-blogs/64713113.yml

avatar: <img src="https://secure.gravatar.com/avatar/28dde5772b48c92e08b8050411aa5ba8?s=80&d=identicon&r=pg" width="64" height="64" />
How wild. I am in the process of migrating away from Disqus on my blog (stephencleary.com) to a very similar solution, for very similar reasons!
Tip: You can use Staticman instead of running your own Function. I've been using Staticman and am very pleased with it. It has reCAPTCHA integration built-in.

Comment by Stephen Cleary on comments-for-jekyll-blogs

---

_includes/post/comments_link.html

Now looks like this:
Not sure why this file currently looks at both post and page variables though. The comment count code is only using post.

Add comment count to archives etc.

---

_data/comments/comments-for-jekyll-blogs/d0cc3e18.yml

> so, someone can increase their “open source contributor” rankings by commenting on your blog? nice! I’ve contributed to the Haacked Blog!
Unfortunately, no. The comments are made under my account. Someday I might allow folks to authenticate using their GitHub account to leave a comment, in which case I would create the commit as your user.

Comment by haacked on comments-for-jekyll-blogs

---

_includes/comment-new.html
_scss/comments.scss
js/comment-box.js

Wrote a simple implementation to enable plaintext contenteditable DIVs on FF. For more details, check out this repo: https://github.com/Haacked/simple-editable-div
Fixes #350

Implement plaintext editable div for Firefox

---

_data/comments/comments-for-jekyll-blogs/b9421556.yml

avatar: <img src="https://github.com/JamesKhoury.png" width="64" height="64" />
This seems like a big security hole. You're creating pull-requests out of user data and as evidenced by a pull-request currently there it will display pictures embedded in the post. I can already think of a couple ways to make this go badly.
At the very least the Pull Request comment should not include the message. Although now I think about it I should go find the repo for the comment system and post that there.

Comment by James on comments-for-jekyll-blogs

---

_data/comments/comments-for-jekyll-blogs/155a3b7a.yml

avatar: <img src="https://avatars.io/twitter/@elliotblackburn/medium" width="64" height="64" />
> Someday I might allow folks to authenticate using their GitHub account to leave a comment
This could be a good way to "trust" users in the future, you could then auto-merge PR's from those users without checking them yourself by having a .github/trusted.yaml file with their github usernames and use some probot implementation to do the review and merge.

Comment by Elliot Blackburn on comments-for-jekyll-blogs

---

_data/comments/comments-for-jekyll-blogs/a9f75c7a.yml

avatar: <img src="https://secure.gravatar.com/avatar/872578c4e56897b913fd03ed88daef51?s=80&d=identicon&r=pg" width="64" height="64" />
> One thing we lose with this approach is a robust comment spam filter. There are two things that mitigate this - first, when you click to send a comment, the button asks you to click again to confirm sending the comment. This is a poor person’s implementation of spam filtering, but seems to get the job done.
Except that a lot of automated spammers just hit the comment API endpoint directly rather than actually using the UI, so a purely UI approach isn't going to stop very much spam :)
For basic spam protection, the best thing I found was to have a input field with a common name (like "name", "subject", whatever), position it off-screen it with CSS, label …

Comment by Daniel15 on comments-for-jekyll-blogs

---

_data/comments/abolish-performance-reviews/e4a81b5d.yml

avatar: <img src="https://avatars.io/twitter/@ericlippert/medium" width="64" height="64" />
Great resource; thanks for putting this together!
My favourite performance review story, about worker W, W's manager M, and M's director D.
W is not doing well on M's team, and M is concerned. W has a great set of skills that are not being used in their current role.  But wait! M has an idea. Team X in the same division has open headcount and needs someone with W's skills.  We'll move W to team X, open up a head on M's team, and hire someone who has the skills needed to make M's team a success. So M puts this plan into effect and W moves over to team X, and coincidentally worker N is available to transfer to M's team, who has the skills needed. Management success!
D comes to M's office and says …

Comment by Eric Lippert on abolish-performance-reviews

---

_data/comments/abolish-performance-reviews/d09b2aec.yml

avatar: <img src="https://avatars.io/twitter/@eeasterberg/medium" width="64" height="64" />
In response to Eric Lippert's comment, the answer to the last paragraph is... every company.
Good post, agree with every single thing in it, but I will expand on one point, giving a counterexample - "Managers have incentives to inflate appraisals."
I once worked in a consulting firm where all reviews were discussed and public to every level of management above. My project was perceived as not doing well (actually our part was fine, long story), and our manager managed to do one thing right - she got herself off the project (wife of a partner, another long story). She later had to do the team's annual performance reviews, and she proceeded to ream every single member. We all received just scathing …

Comment by Eric Easterberg on abolish-performance-reviews

---

_data/comments/i-knew-how-to-validate-an-email-address-until-i-aspx/368b0f0c.yml

avatar: <img src="https://secure.gravatar.com/avatar/292e4984bb764a41d326fa4f9848428d?s=80&d=identicon&r=pg" width="64" height="64" />
For information's sake: ! in an email address is a relic from email in the pre-internet era (before, or by places that were not connected to, ARPANET or BITNET, typically). At that point, uucp was used to copy data in batches from one machine to another, by modem. If your machine didn't connect directly to another machine, and didn't know a valid route to it, you would have to give it the route: machine1!machine2!machine3. Another such mechanism was the percent sign. If you knew the way to a machine that knew the way to where you wanted to send your email, you could just say  someone%destination@somewhere-else. Your server would send the message …

Comment by Fred Fnord on i-knew-how-to-validate-an-email-address-until-i-aspx

---

_data/comments/abolish-performance-reviews/cbabe67e.yml

avatar: <img src="https://avatars.io/twitter/@travislaborde/medium" width="64" height="64" />
Phil, I agree with you but I think you've failed to mention the real point behind the performance reviews these days:  HR and Legal.
So many companies use these as their "backup" in the case that a dismissed employee files a grievance of some sort.  It is seen as "documentation" that the person was warned, and had ample time to improve before being let go.
I think a company wants to frame the performance review in a positive light, but that's just double-speak when the real goal is to use it as a hammer or as insurance.

Comment by Travis Laborde on abolish-performance-reviews

---

_data/comments/abolish-performance-reviews/422f8d7e.yml

> “Pay according to the market instead.” What ever happened to paying what your worth?
I definitely agree with employers paying what employees are worth. But let me ask you, how do you determine worth?
The market is one good means to do that. In most cases, when I say "Pay according to the market" I'm equating that with "Pay what people are worth."
Note that I'm not saying every company has to pay top of market. But I would suggest indexing to the market. For example, if your company says it'll pay 95% of market, then that company should evaluate the market on a periodic basis and give raises every time the market value goes up.
DHH [notes they do this at …

Comment by haacked on abolish-performance-reviews

---

_data/comments/fixing-binding-to-decimals-aspx/ad3ccf25.yml

avatar: <img src="https://secure.gravatar.com/avatar/1443d600ab7f230a27cc1a4c55459610?s=80&d=identicon&r=pg" width="64" height="64" />
It seems not to work when your model has another class with decimal property. Default model binder is going to try bind this property.

Comment by Andrej on fixing-binding-to-decimals-aspx

---

_data/comments/comments-for-jekyll-blogs/da4c95ce.yml

avatar: <img src="https://secure.gravatar.com/avatar/d888f0a1a5f7edfec38628e78fcfd0e5?s=80&d=identicon&r=pg" width="64" height="64" />
Found this while trying to figure out how to add comments to my own Jekyll blog. I wanted to use staticman, but the first XSS comment I submitted to my blog popped an alert immediately, so I've steered away from that. Does this have any kind of filtering protections? Or does that have to be built into the azure function?

Comment by gr0k on comments-for-jekyll-blogs

---

_data/comments/fixing-binding-to-decimals-aspx/b9fe2d82.yml

avatar: <img src="https://secure.gravatar.com/avatar/770aa719b7b6349f833f25027858b230?s=80&d=identicon&r=pg" width="64" height="64" />
this solution don't work for italian culture because the separator is ,
you must use en-GB culture

Comment by Alessandro Lettieri on fixing-binding-to-decimals-aspx

---

_data/comments/structuring-unit-tests-aspx/972efd25.yml

avatar: <img src="https://secure.gravatar.com/avatar/2a2f0116be79c06f3277c8b168ebd4b1?s=80&d=identicon&r=pg" width="64" height="64" />
Well, if you use nested classes for collapsing, why not use regions instead?

Comment by Zoran on structuring-unit-tests-aspx

---

_data/comments/i-knew-how-to-validate-an-email-address-until-i-aspx/79b574ca.yml

avatar: <img src="https://secure.gravatar.com/avatar/cf6b905762dda1df8b5adedd0b2d022f?s=80&d=identicon&r=pg" width="64" height="64" />
The validation fails on `a.example@gmx.ch' which it's a correct email address. Any idea?

Comment by Babak on i-knew-how-to-validate-an-email-address-until-i-aspx

---

_data/comments/comments-for-jekyll-blogs/5cbce8f1.yml

avatar: <img src="https://avatars.io/twitter/@Seanba_/medium" width="64" height="64" />
I like the changes you made to the Jekyll templates that fetch and remember the avatar image without sending any user identity up to the cloud (or back into your gh-pages PRs). I see your javascript employs the HAACK namespace and wanted to double-check that such code is still considered to be under the MIT license. (Thanks for showing your work all the same. I'm looking forward to getting my blog off the wordpress and webhosting teats.)

Comment by Sean on comments-for-jekyll-blogs

---

_data/comments/url-routing-debugger-aspx/0f42cbfc.yml

avatar: <img src="https://secure.gravatar.com/avatar/36e80e7203558664ba9241881ee9744e?s=80&d=identicon&r=pg" width="64" height="64" />
Seems like the zip files are not longer available in this article.... Any way to use the debugger without the route tester tool?

Comment by Martin on url-routing-debugger-aspx

---

_data/comments/law-of-demeter-dot-counting-aspx/89bda294.yml

avatar: <img src="https://secure.gravatar.com/avatar/20d2a4bdb669825acaa0a18806d3222b?s=80&d=identicon&r=pg" width="64" height="64" />
I think the problem with violating LoD in view you mentioned is not relevant because of separation of concerns. If some data has to be shown in view clearly what we want is a data structure and not a object. Just think about what happen if we pas an object with behavior to view? One could accidentally mutat object state in view! So in this case maybe we must ask the order object for a read only representation of its data (whic it can control to what it expose) as a data structure. As uncle Bob said in his great book “clean code”, law of demeter depends on if class is an object or data structure.

Comment by Omid Khadem on law-of-demeter-dot-counting-aspx

---

Gemfile
Gemfile.lock
_config.yml
_layouts/default.html

The header rendering no longer depends on the current page. It's the same for every page. The theme now selects the current page using JS. This cuts down build time from 390 seconds to 39 seconds!

Fix header caching

---

_posts/2019/2019-06-24-semantic-merge-conflicts.markdown

System.Console is a class, not a namespace. This was pointed out by https://twitter.com/dgmarious/status/1143708826014822401?s=21
It doesn't detract from the point of the post, but might as well make it more realistic.

Replace fake namespace with real namespace

---

_posts/2020/2020-05-17-french-thousand-separator-mystery.md

Your code output isn't displaying on multiple lines as was probably intended.
Makes spotting the change in the hex from line 1 to line 2 hard (as its all one line).

Fix line breaks in code output

---

_posts/archived/2014/2014-07-28-github-flow-aliases.markdown

"CURRENT" was rename to "DEFAULT" but these three uses were missed.

Update the default variable used in explanations

---

_posts/2019/2019-02-14-including-git-aliases.markdown

Finally installing your aliases and the link to https://raw.githubusercontent.com/Haacked/dotfiles/main/git/.gitconfig.aliases 404s

Fix 404 link to gitconfig.aliases from "Include my Git Aliases" blog post

---

_posts/2021/2021-09-01-hosted-csharp-intellisense.md

Blogged: Abbot provides a custom C# script host for skills. Unfortunately, your local editor doesn't know anything about that, so we did some dark arts to make IntelliSense work anyways.

Blogged: IntelliSense for Hosted C# Scripts

---

_data/comments/three-hidden-extensibility-gems-in-asp-net-4-aspx/a5e208cb.yml

@Frode, regarding your error message "An error occurred creating the configuration section handler for testproject: This method cannot be called during the application's pre-start initialization stage." see this post:
https://weblogs.asp.net/pglavich/entity-framework-and-the-preapplicationstartmethod-attribute

Comment by pholpar on three-hidden-extensibility-gems-in-asp-net-4-aspx

---

_data/comments/model-binding-to-a-list-aspx/d4fa109f.yml

avatar: <img src="https://secure.gravatar.com/avatar/d4413afed1a86a0cf24fb76bf7de9888?s=80&d=identicon&r=pg" width="64" height="64" />
Hello, Phil! How are you doing? Thanks for the article, it was very helpful!
Hi @Joshua and @KevinUK, I've got the same problem, and here's the solution:
You have to add a new input hidden for your new sublist, including the index of the previous one. Here's the example that worked for me.
<input type="hidden" name"products[0].categories.Index" value="0">

Comment by João Paulo Rodrigues Santos on model-binding-to-a-list-aspx

---

_data/comments/display-template-tag-helper/00d96aa3.yml

avatar: <img src="https://secure.gravatar.com/avatar/1293f1ffe5da2109554b87dc38510625?s=80&d=identicon&r=pg" width="64" height="64" />
`TagHelperPack` does not work out of the box. Using ASP.NET Core 6 MVC and `DisplayNameForTagHelper`fails for `For` in `output.PostContent.AppendHtml(_htmlHelper.DisplayName(For));`.
Also, it does not work at all, if page model is `@model IEnumerable<Student>;` (and no for-each). But `@Html.DisplayNameFor(model => model.FurstName)` works fine (using it for column header in table).

Comment by WasPassingBy on display-template-tag-helper

---

_data/comments/ef-core-collection-pitfalls/bc61f48e.yml

avatar: <img src="https://unavatar.now.sh/twitter/haacked/" width="64" height="64" />
@Joel, I'm using EF Core and defined my collection property as an `IList<T>` which is populated with a `List<T>`. `List<T>` is a standard .NET collection and doesn't know anything about EF so it wouldn't be able to load the collection.
In theory, I could create a custom collection type that does all that, but I'm not a fan of implicit database queries. I'd rather be explicit about when my code calls the database. It's too easy to run into problems and N+1 issues otherwise.

Comment by haacked on ef-core-collection-pitfalls

---

_data/comments/ef-core-collection-pitfalls/f6e3a3d5.yml

avatar: <img src="https://secure.gravatar.com/avatar/9892eb80b286090fda750586e1bd975c?s=80&d=identicon&r=pg" width="64" height="64" />
@haacked. Thank you. I've never used EF so I'm not familiar with it. I would have expected the ORM to populate the IList with a type that does the implicit query like you describe, not just a standard List. But I agree that hidden database queries like that should be avoided.

Comment by Joel on ef-core-collection-pitfalls

---

_data/comments/calculating-mrr-with-stripe-and-csharp/2dabbcae.yml

avatar: <img src="https://unavatar.now.sh/twitter/SeanKilleen.com/" width="64" height="64" />
Is this different than Stripe Metrics export? https://stripe.com/docs/billing/subscriptions/view-metrics#metrics-export
The metrics export includes MRR per subscriber per month and MRR roll-forward, active subscriber roll-forward, etc.
Regardless, this is a great walkthrough! And I agree, Stripe support is awesome.

Comment by Sean Killeen on calculating-mrr-with-stripe-and-csharp

---

_data/comments/calculating-mrr-with-stripe-and-csharp/d5e529d5.yml

Does your code handle the scenario where a user purchases something on an already started yearly subscription in the middle of the service period?
E.g. in our own setup, a user can purchase extra seats on their yearly volume license subscription. The expiration for these seats are cotermed to the volume license expiration, thus the price is of course reduced because they're not covering a full period, and thus the MRR is obviously not 1/12, but rather the remaining period, e.g. 1/6 if purchased half-way through the period.
Also, I think it would be beneficial to have code that supports point-in-time calculations of MRR, such that development of MRR over time can be calculated/plotted.
It's an interesting topic, …

Comment by Sol on calculating-mrr-with-stripe-and-csharp

---

_data/comments/recover-from-dbupdate-exception/4776128f.yml

avatar: <img src="https://github.com/stevehansen.png" width="64" height="64" />
Shouldn't the detach be done on the user variable before you assigned it with the database value? I would guess that they both be different instances in memory

Comment by Steve on recover-from-dbupdate-exception

---

_data/comments/recover-from-dbupdate-exception/7ccc0c08.yml

avatar: <img src="https://github.com/thoemmi.png" width="64" height="64" />
Ahem, in the last code snippet, ~Phil~ Bill wants to detach the *new* User instance, not that one returned by the second SingleOrDefaultAsync call, right?

Comment by Thomas Freudenberg on recover-from-dbupdate-exception

---

_data/comments/recover-from-dbupdate-exception/c3add191.yml

avatar: <img src="https://unavatar.now.sh/twitter/haacked/" width="64" height="64" />
Thomas and Steve, you're absolutely correct! This is what happens when I try to transcribe code and simplify it for brevity. I just posted an update with the correct code. We want to query to a new variable. We only want to detach if we're going to recover.

Comment by haacked on recover-from-dbupdate-exception

---

_data/comments/recover-from-dbupdate-exception/af20c3ed.yml

avatar: <img src="https://unavatar.now.sh/twitter/przemsen/" width="64" height="64" />
DbContext is not supposed to be thread safe. Why are allowing your repository method to be executed concurrently from multiple threads?

Comment by Przemyslaw on recover-from-dbupdate-exception

---

_data/comments/scoping-db-context/0bed6d4f.yml

avatar: <img src="https://secure.gravatar.com/avatar/48271d3706d8d398c0dbc5645cb8b51d?s=80&d=identicon&r=pg" width="64" height="64" />
I think you can achieve the same through a much easier method. Call AddDbContextFactory() before AddDbContext(). This will create a DbContextOptions with singleton lifetime, that can be then consumed by AddDbContext. I even made a video on that in the context of Blazor Server.

Comment by Dan on scoping-db-context

---

_data/comments/calling-internal-ctors/2559193d.yml

avatar: <img src="https://robohash.org/07679baf203e4889a483b09c247179cc" width="64" height="64" />
With the Azure SDKs for .NET, we provide a *ModelFactory for response models. With clients we make all members virtual, but callvirt is an unnecessarily expensive call for models' members. See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyModelFactory.cs for an example for Key Vault.
Alas, the OpenAIClient library does not generate a model factory. https://github.com/Azure/azure-sdk-for-net/issues/35189 may be tracking, but I commented to follow up.

Comment by Heath on calling-internal-ctors

---

_data/comments/calling-internal-ctors/7391ccf9.yml

avatar: <img src="https://robohash.org/d3ac734987a53355ae6cf6d885ccdf0c" width="64" height="64" />
The one downside to the Instantiate<T> utility method I can see is that it cannot deal with parameters that are null.

Comment by Jesse Slicer on calling-internal-ctors

---

_data/comments/law-of-demeter-dot-counting-aspx/4040316c.yml

avatar: <img src="https://github.com/Zackhardtoname.png" width="64" height="64" />
It seems to me that LOD is especially useful/applicable if the object returned from an violation goes through various transformation such as the wallet example. However, if there are not any transformation logic, as in the UI & driver's license example. We could justify it by saying one of the chained objects serve as containers, and the violation is okay.

Comment by Zack Light on law-of-demeter-dot-counting-aspx

---

_data/comments/failure/322dee01.yml

You made some important points about the .NET stack, which I too struggle with. Been using it since version 1.0, but now I feel like I wish it could be interpreted during development - and of course that'll never happen.
So, what is your next tech stack? This is a VERY important conversion, one we've been having internally here for years.
.NET is (no longer) as agile as it was, and neither is Java, Rust, Go, etc. (even though awesome and fast in production). So what else? Python is wonderful in dev, but terribly slow in prod. Rails is nice, but it's just not "a thing" in most companies, and there's no talent. What else? Bear with me, don't laugh... There's Perl which is old, but it's blazing …

Comment by Lee on failure

---

_data/comments/external-claims/3f539b07.yml

avatar: <img src="https://secure.gravatar.com/avatar/2523ef835f2b054a1d6291bf5f66e688?s=80&d=identicon&r=pg" width="64" height="64" />
I have implemented IUserClaimsPrincipalFactory and it seems that there is no need to inject SignInManager.
public async override Task<ClaimsPrincipal> CreateAsync(User user)
{
var principal = await base.CreateAsync(user);
if (principal.Identity is ClaimsIdentity claimsIdentity)
{
var httpContext = _httpContextAccessor.HttpContext;
if (httpContext != null)
{
var auth = await httpContext.AuthenticateAsync(IdentityConstants.ExternalScheme);
var authClaims = auth.Principal?.Claims;
if (authClaims != null)
{
claimsIdentity.AddClaims(authClaims);
}
}
}
return principal;
}

Comment by DaN on external-claims

---

_data/comments/github-flow-aliases/96ab5100.yml

avatar: <img src="https://robohash.org/7147b1fc151de120fbc956ba90be1d37" width="64" height="64" />
To avoid "fatal: branch name required" add the --no-run-if-empty flag to xargs in bclean

Comment by James on github-flow-aliases

---

_data/comments/dotnet-aspire-vs-docker/9a47e441.yml

I get a 404 for this link 
https://github.com/haacked/docker-efcore-postgres-demo

Comment by Oskar Gewalli on dotnet-aspire-vs-docker

---

_data/comments/better-config-sections/2fc5d1da.yml

avatar: <img src="https://github.com/RMcD.png" width="64" height="64" />
I've used a similar pattern on my options objects in the past by creating a unit test that uses conventions and reflection to validate all of the options classes/records have a static field for Configuration name with a non-null value. CI then fails it someone adds an options object without one. The configuration section name is used in builder extensions to have each option class identify the section with which it binds.
I like this as an option (haha) though. I'll have to give it a spin.

Comment by Rafferty McDonald on better-config-sections

---

_posts/archived/2016/2016-02-29-regex-turkish-i.markdown

Add Pyrexp (my website), an online visual regex tester for Python, to "Useful online tools" /  2016-02-29-regex-turkish-i.markdown
And fix the URLs for other resources (replace 'http' with 'https').

Add Pyrexp to "Useful online tools" /  2016-02-29-regex-turkish-i.markdown

---

_data/comments/git-bisect/15ded58d.yml

avatar: <img src="https://secure.gravatar.com/avatar/5fc7c28e6b6e01c5b61e1b1e6ce78bba?s=80&d=identicon&r=pg" width="64" height="64" />
If you are using a PR workflow with CI testing and merge commits you can use the first-parent flag for git bisect in your main branch (or other CI enforced integration branch) to first determine which PR (merge commit) introduced the bug. I find this pass can often be easily automated (because your CI system already enforced that they build). Sometimes knowing the PR can be all you need, too. If you do need to drill down into which commit inside a PR, you branch the “second parent” and you can again benefit from the first-parent flag to test only the PR’s “own” not any commits brought in from other branches. (You could keep drilling down at that point, but …

Comment by Max on git-bisect

---

_data/comments/ef-core-collection-pitfalls/3ec13ac8.yml

I wish there was a good solution for this. It should "explode" (throw) if I try to access a collection that I haven't included (when not lazy loading). This is a case where a runtime exception would actually be an improvement over the default. Just silently giving an empty collection is really frustrating and I can't seem to find a good alternative.

Comment by Dave on ef-core-collection-pitfalls

---

_data/comments/git-gone/fc89e8bc.yml

avatar: <img src="https://secure.gravatar.com/avatar/5fc7c28e6b6e01c5b61e1b1e6ce78bba?s=80&d=identicon&r=pg" width="64" height="64" />
With squash merging I become a branch hoarder. I’ve been saved too many times with archeology into my own loose commits to force delete squash merged branches, so I’ve taken to just renaming them with a useful prefix instead. In my case that prefix is currently zoo/ because it sorts nicely to the bottom and a lot of my branches include adjective-animal random names. I have found it also helps when having set —update-refs as a default to rebase because when the git merge algorithm gets confused with squash merges (which it does, surprisingly often) and tries to update-ref a zoo/ branch you know exactly which commits you can simply “drop” from the rebase …

Comment by Max on git-gone

---

_data/comments/github-flow-aliases/9115e527.yml

avatar: <img src="https://secure.gravatar.com/avatar/822b8208457f2ece6e192bdd88f496bd?s=80&d=identicon&r=pg" width="64" height="64" />
my most used alias is "recent". It allows me to quickly switch to a recent checked out branch  (of which I usually don't know the exact name anymore) by using an index:
recent = !sh ~/recent.sh
recent.sh:
----------------
MAX_NUMBER_OF_BRANCHES_TO_DISPLAY=10
if [ -n "$1" ]; then
git checkout $(git reflog | egrep -io "moving from ([^[:space:]]+)" | awk '{ print $3 }' | awk ' !x[$0]++' | egrep -v '^[a-f0-9]{40}$' | egrep -v 'main' | head -n$1 | tail -n1)
else
git reflog | egrep -io "moving from ([^[:space:]]+)" | awk '{ print $3 }' | awk ' !x[$0]++' | egrep -v '^[a-f0-9]{40}$' | egrep -v 'main' | head -n$MAX_NUMBER_OF_BRANCHES_TO_DISPLAY | nl -v 1
fi

Comment by HerrDerb on github-flow-aliases
